RazorPagesDemo/RazorPagesDemo/Pages/ContactMe.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using System.Net.Mail;
using System.Text.RegularExpressions;

namespace RazorPagesDemo.Pages
{
    public class ContactMeModel : PageModel
    {
        private readonly IConfiguration Configuration;

        public ContactMeModel(IConfiguration configuration)
        {
            Configuration = configuration;  
        }


        [BindProperty]
        public string? ContactName { get; set; }

        [BindProperty]
        public string? ContactEmail { get; set; }

        [BindProperty]
        public string? ContactComments { get; set; }

        [BindProperty]
        public Boolean SubscribeToMail { get; set; } = true;

        public string InfoMessage { get; private set; }

        public string ErrorMessage { get; private set; }

        public void OnPostSendMessage()
        {
            if (string.IsNullOrWhiteSpace(ContactName))
            {
                ModelState.AddModelError(nameof(ContactName), "Contact Name is required and cannot be blank");
            }
            else if(ContactName.Length < 5)
            {
                ModelState.AddModelError(nameof(ContactName), "Contact Name must contain 5 or more characters");
            }
            if (string.IsNullOrWhiteSpace(ContactEmail))
            {
                ModelState.AddModelError(nameof(ContactEmail), "Contact Email is required and cannot be blank");
            }
            else if (!ContactEmail.Contains("@") || !ContactEmail.Contains(".com"))
            {
                ModelState.AddModelError(nameof(ContactName), "Contact Email must contain 5 or more characters");
            }

            if (ModelState.IsValid)
            {
                string subscribeToMail = (SubscribeToMail == true) ? "Yes" : "No";
                InfoMessage = $"Name: {ContactName} <br />"
                    + $"Email: {ContactEmail} <br />"
                    + $"Comments: {ContactComments} <br />"
                    + $"Subscribe to mail: {subscribeToMail}";

                SmtpClient sendMailClient = new();
                sendMailClient.Host = Configuration["MailServerSettings:SmtpHost"];
                sendMailClient.Port = int.Parse(Configuration["MailServerSettings:Port"]);
                sendMailClient.EnableSsl = bool.Parse(Configuration["MailServerSettings:EnableSsl"]);

                NetworkCredential mailCredentials = new();
                mailCredentials.UserName = Configuration["MailServerSettings:Username"];
                mailCredentials.Password = Configuration["MailServerSettings:AppPassword"];
                sendMailClient.Credentials = mailCredentials;

                string mailToAddress = ContactEmail ?? Configuration["MailServerSettings:Email"];
                string mailFromAddress = Configuration["MailServerSettings:Email"];

                MailMessage mailMessage = new MailMessage(mailFromAddress, mailToAddress);
                mailMessage.Subject = "CPSC1517 new contact me form submission";
                mailMessage.Body = InfoMessage;

                try
                {
                    sendMailClient.Send(mailMessage);
                    ContactName = null;
                    ContactEmail = null;
                    ContactComments = null;
                    InfoMessage = "Your message has been sent";
                }
                catch (Exception ex)
                {
                    ErrorMessage = $"Error sending mail with exception: {ex.Message}";
                }
            }
        }
        public IActionResult OnPostClear()
        {
            ContactName = null;
            ContactEmail = null;
            ContactComments = null;
            SubscribeToMail = true;
            return RedirectToPage();
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorPagesDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public DateTime CurrentDateTime { get; private set; } = DateTime.Now;

        public int LuckyNumber { get; private set; } = 15;

        public void OnGet() // This method gets executed in response to an HTTP GET request
        {
            var rand = new Random();
            LuckyNumber = rand.Next(1, 51);
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/LottoQuickPickd.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class LottoQuickPickdModel : PageModel
    {
        [BindProperty]
        public string? UserName { get; set; }
        [BindProperty]
        public string LottoType { get; set; }
        [BindProperty]
        public int QuickPickQuantity { get; set; }

        public string? InfoMessage { get; set; }
        public string? ErrorMessage { get; set; }

        public List<int[]> QuickPickNumbers { get; private set; } = new();

        Random random = new Random();
        public void OnPost()
        {
            if(string.IsNullOrWhiteSpace(UserName))
            {
                ErrorMessage = "Name is required";
            }
            else
            {
                InfoMessage = $"Hello {UserName}";
                //Clear the quick pick numbers
                QuickPickNumbers.Clear();
                for(int arrayNumber = 1; arrayNumber <= QuickPickQuantity; arrayNumber++)
                {
                    if (LottoType.ToUpper() == "LOTTO649")
                    {
                        int[] current649Picks = new int[6]; 
                        for(int count = 1; count <= 6; count++)
                        {
                            current649Picks[count - 1] = random.Next(1, 49);
                        }

                        Array.Sort(current649Picks);
                        QuickPickNumbers.Add(current649Picks);
                    }
                }
            }
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/MultiplicationTable.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesDemo.Pages.Models;

namespace RazorPagesDemo.Pages
{
    public class MultiplicationTableModel : PageModel
    {
        [BindProperty]
        public int DigitRow { get; set; }
        [BindProperty]
        public int DigitColumn { get; set; }

        public TableType? Type { get; set; }

        public void OnPostMultiply()
        {
            Type = TableType.Multiply;
        }

        public void OnPostAdd()
        {
            Type = TableType.Add;
        }

        public void OnPostSubtract()
        {
            Type = TableType.Subtract;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/RollDice.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class RollDiceModel : PageModel
    {
        public void OnGet()
        {
            DiceFaceValueImage = "img/icons/ffffff/000000/1x1/delapouite/dice-shield.png";
        }

        public int DiceFaceValue { get; private set; }
        public string DiceFaceValueImage { get; private set; }

        [BindProperty]
        public int BetAmount { get; set; }
        [BindProperty]
        public int SelectedDiceSide { get; set; }

        public string InfoMessage { get; set; }

        public string[] DiceImages = 
        {
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-one.png",
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-two.png",
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-three.png",
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-four.png",
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-five.png",
            "img/icons/ffffff/000000/1x1/delapouite/dice-six-faces-six.png",
        };

        public void OnPost()
        {
            var rand = new Random();
            DiceFaceValue = rand.Next(1, 7);
            DiceFaceValueImage = DiceImages[DiceFaceValue - 1];

            if(DiceFaceValue == SelectedDiceSide)
            {
                InfoMessage = $"You Won {BetAmount:C}";
            }
            else
            {
                InfoMessage = $"You Lost {BetAmount:C}";
            }
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/SimpleCalculator.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesDemo.Pages
{
    public class SimpleCalculatorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesDemo/RazorPagesDemo/Pages/ContactMe.cshtml
@page
@model RazorPagesDemo.Pages.ContactMeModel
@{
    ViewData["Title"] = "Contact Me";
}
<h1>Contact Me</h1>

@if (Model.InfoMessage is not null) 
{
    <div class="alert alert-info">
        @Html.Raw(Model.InfoMessage)
    </div>
}
@if (Model.ErrorMessage is not null) 
{
    <div class="alert alert-warning">
        @Html.Raw(Model.ErrorMessage)
    </div>
}

<div asp-validation-summary="All" class="text-danger">
    @if(ModelState.Count > 0){
        <p>Please fix the following issues</p>
    }
</div>

<form method="post">
    <div class="row mb-3">
        <label asp-for="ContactName" class="col-sm-2 col-form-label">Your Name</label>
        <div class="col-sm-10">
            <input asp-for="ContactName" class="form-control" >
        </div>
        <span asp-validation-for="ContactName" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label asp-for="ContactEmail" class="col-sm-2 col-form-label">Your Email</label>
        <div class="col-sm-10">
            <input asp-for="ContactEmail" type="email" class="form-control" >
        </div>
        <span asp-validation-for="ContactEmail" class="text-danger"></span>
    </div>
    <div class="row mb-3">
        <label asp-for="ContactComments" class="col-sm-2 col-form-label">Your Comments</label>
        <div class="col-sm-10">
            <textarea asp-for="ContactComments" 
                rows="5" cols="50"    
                class="form-control">
            </textarea>
        </div>
    </div>    
    <div class="row mb-3">
        <div class="col-sm-10 offset-sm-2">
            <div class="form-check">
                <input asp-for="SubscribeToMail" class="form-check-input" type="checkbox" >
                <label asp-for="SubscribeToMail" class="form-check-label">
                    Subscribe to Mail
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <button type="submit" asp-page-handler="SendMessage" class="btn btn-primary">Send Message</button>
        <button type="submit" asp-page-handler="Clear" class="btn btn-secondary">Clear</button>
        <button type="reset" class="btn btn-info">Reset</button>
    </div>
</form>

RazorPagesDemo/RazorPagesDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
    <h2 style="color: rebeccapurple">Hello World from ASP.NET Razor Pages</h2>

    <p>The current date time @Model.CurrentDateTime.ToString()</p>

    <div style="background-color:steelblue">
        <h3>@Model.LuckyNumber</h3>
    </div>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RazorPagesDemo/RazorPagesDemo/Pages/LottoQuickPickd.cshtml
@page
@model RazorPagesDemo.Pages.LottoQuickPickdModel
@{
}

@if(Model.InfoMessage is not null){
    <div class="alert-info">
        <p>@(Model.InfoMessage)</p>
    </div>
}
@if (Model.ErrorMessage is not null)
{
    <div class="alert-danger">
        <p>@(Model.ErrorMessage)</p>
    </div>
}
<h1>Lotto Quick Picks</h1>
<form method="post">
    <div>
        <label>Name</label>
        <input type="text" placeholder="Enter Name" class="form-control" asp-for="UserName" aria-label="UserName">
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="LottoMax" id="LottoMax">
        <label class="form-check-label" for="LottoMax">
            LottoMax
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="Lotto649" id="Lotto649" checked>
        <label class="form-check-label" for="Lotto649">
            Lotto649
        </label>
    </div>
    <button type ="submit" class="btn btn-primary">Generate</button>
</form>

RazorPagesDemo/RazorPagesDemo/Pages/MultiplicationTable.cshtml
@page
@model RazorPagesDemo.Pages.MultiplicationTableModel
@{
}
<h1>Multiplication Table</h1>

<form method="post">
    <div class="row">
        <div class="col">
            <input type="number" min="1" max="100" class="form-control" placeholder="Rows" aria-label="DigitRow" asp-for="DigitRow">
        </div>
        <div class="col">
            <input type="number" min="1" max="100" class="form-control" placeholder="Columns" aria-label="DigitColumn" asp-for="DigitColumn">
        </div>
    </div>
    <div class="row">
        <button type="submit" class="btn btn-primary" asp-page-handler="Multiply">Generate Multiplication Table</button>
        <button type="submit" class="btn btn-success" asp-page-handler="Add">Generate Addition Table</button>
        <button type="submit" class="btn btn-info" asp-page-handler="Subtract">Generate Subtraction Table</button>
    </div>
</form>

@if (Model.Type != null)
{
    <table class="table table-bordered">

        <tr>
            <td> </td>
            @for (int currentRow = 1; currentRow <= Model.DigitRow; currentRow++)
            {
                <td style="background-color: forestgreen;">@(currentRow)</td>
            }
        </tr>
        @for (int currentRow = 1; currentRow <= Model.DigitRow; currentRow++)
        {
            <tr>
                <td style="background-color: forestgreen;">@(currentRow)</td>
                @for (int currentColumn = 1; currentColumn <= Model.DigitRow; currentColumn++)
                {
                    @if(currentColumn == currentRow)
                    {
                        @if(Model.Type == Models.TableType.Multiply){
                            <td style="background-color: orange;">@(currentRow * currentColumn)</td>
                        }
                        else if (Model.Type == Models.TableType.Add)
                        {
                            <td style="background-color: orange;">@(currentRow + currentColumn)</td>
                        }
                        else{
                            <td style="background-color: orange;">@(currentRow - currentColumn)</td>
                        }
                        
                    }
                    else{
                        @if (Model.Type == Models.TableType.Multiply)
                        {
                            <td>@(currentRow * currentColumn)</td>
                        }
                        else if (Model.Type == Models.TableType.Add)
                        {
                            <td>@(currentRow + currentColumn)</td>
                        }
                       else
                        {
                            <td>@(currentRow - currentColumn)</td>
                        }
                    }
                }
            </tr>
        }
    </table>
}

RazorPagesDemo/RazorPagesDemo/Pages/RollDice.cshtml
@page
@model RazorPagesDemo.Pages.RollDiceModel
@{
}
<div class="text-center">
    <h1>Six-Sided Dice Roll Simulator</h1>
    <img src="@Model.DiceFaceValueImage"
         alt="Dice Image"
         width="200px"
         height="200px" />

    @if (Model.InfoMessage != null)
    {
        <div>
            <p>@Model.InfoMessage</p>
        </div>
    }

    <form method="post">

        <div>
            <label for="BetAmount">Bet Amount</label>
            <input type="number" min="1" max="20" id="BetAmount" name="BetAmount" value="@Model.BetAmount">
        </div>

        <div>
            <label for="SelectedDiceSide" class="form-text">Bet Number</label>
            <select class="form-select" id="SelectedDiceSide" name="SelectedDiceSide">
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="4">Four</option>
                <option value="5">Five</option>
                <option value="6">Six</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Roll Dice</button>
    </form>
</div>

RazorPagesDemo/RazorPagesDemo/Pages/SimpleCalculator.cshtml
@page
@model RazorPagesDemo.Pages.SimpleCalculatorModel
@{
}